package com.example.projprogavanc

import android.content.ContentUris
import android.database.Cursor
import android.net.Uri
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.MenuItem
import android.view.View
import android.view.ViewGroup
import android.widget.SimpleCursorAdapter
import android.widget.Spinner
import android.widget.Toast
import androidx.loader.app.LoaderManager
import androidx.loader.content.CursorLoader
import androidx.loader.content.Loader
import androidx.navigation.fragment.findNavController
import com.example.projprogavanc.databinding.FragmentEditStoreBinding


class EditStoreFragment : Fragment(), LoaderManager.LoaderCallbacks<Cursor> {
    private var _binding: FragmentEditStoreBinding? = null

    private val binding get() = _binding!!

    private var store :Store? =null

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        _binding = FragmentEditStoreBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val activity = activity as MainActivity
        activity.fragment = this
        activity.currMenuId = R.menu.edit_menu

        if(arguments != null){
            store = EditStoreFragmentArgs.fromBundle(arguments!!).store

            if(store != null){
                binding.editTextStoreName.setText(store!!.name)
                binding.editTextStoreAddress.setText(store!!.address)

            }

        }

        LoaderManager.getInstance(this).initLoader(ID_LOADER_STORETYPE, null, this)
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    companion object {
        const val ID_LOADER_STORETYPE = 0
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param id The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    override fun onCreateLoader(id: Int, args: Bundle?): Loader<Cursor> =
        CursorLoader(
            requireContext(),
            ContentProviderGameStore.STORETYPES_ADDRESS,
            TDBStoreTypes.ALL_COLUMNS,
            null,
            null,
            TDBStoreTypes.C_TYPE
        )


    /**
     * Called when a previously created loader has finished its load.  Note
     * that normally an application is *not* allowed to commit fragment
     * transactions while in this call, since it can happen after an
     * activity's state is saved.  See [ FragmentManager.openTransaction()][androidx.fragment.app.FragmentManager.beginTransaction] for further discussion on this.
     *
     *
     * This function is guaranteed to be called prior to the release of
     * the last data that was supplied for this Loader.  At this point
     * you should remove all use of the old data (since it will be released
     * soon), but should not do your own release of the data since its Loader
     * owns it and will take care of that.  The Loader will take care of
     * management of its data so you don't have to.  In particular:
     *
     *
     *  *
     *
     *The Loader will monitor for changes to the data, and report
     * them to you through new calls here.  You should not monitor the
     * data yourself.  For example, if the data is a [android.database.Cursor]
     * and you place it in a [android.widget.CursorAdapter], use
     * the [android.widget.CursorAdapter.CursorAdapter] constructor *without* passing
     * in either [android.widget.CursorAdapter.FLAG_AUTO_REQUERY]
     * or [android.widget.CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER]
     * (that is, use 0 for the flags argument).  This prevents the CursorAdapter
     * from doing its own observing of the Cursor, which is not needed since
     * when a change happens you will get a new Cursor throw another call
     * here.
     *  *  The Loader will release the data once it knows the application
     * is no longer using it.  For example, if the data is
     * a [android.database.Cursor] from a [android.content.CursorLoader],
     * you should not call close() on it yourself.  If the Cursor is being placed in a
     * [android.widget.CursorAdapter], you should use the
     * [android.widget.CursorAdapter.swapCursor]
     * method so that the old Cursor is not closed.
     *
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that has finished.
     * @param data The data generated by the Loader.
     */
    override fun onLoadFinished(loader: Loader<Cursor>, data: Cursor?) {
        val adapterStoreType = SimpleCursorAdapter(
            requireContext(),
            android.R.layout.simple_list_item_1,
            data,
            arrayOf(TDBStoreTypes.C_TYPE),
            intArrayOf(android.R.id.text1),
            0
        )

        binding.spinnerStoreType.adapter = adapterStoreType

        updateSelectedStoreType()
    }

    private fun updateSelectedStoreType() {
        if(store == null) return

        val storeTypeId = store!!.type.id

        val lastStoreType = binding.spinnerStoreType.count - 1

        for (i in 0..lastStoreType){
            if(binding.spinnerStoreType.getItemIdAtPosition(i) == storeTypeId) {
                binding.spinnerStoreType.setSelection(i)
                return
            }
        }
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that is being reset.
     */
    override fun onLoaderReset(loader: Loader<Cursor>) {
        if(_binding == null) return
        binding.spinnerStoreType.adapter = null
    }

    fun processOptionMenu(item: MenuItem): Boolean =
        when(item.itemId){
            R.id.action_save ->{
                save()
                true
            }
            R.id.action_cancel ->{
                backtoStoreList()
                true
            }
            else -> false
        }

    private fun save() {

        val StoreName = binding.editTextStoreName.text.toString()
        if(StoreName.isBlank()){
            binding.editTextStoreName.error = getString(R.string.name_error)
            binding.editTextStoreName.requestFocus()
            return

        }

        val StoreAddress = binding.editTextStoreAddress.text.toString()
        if(StoreAddress.isBlank()){
            binding.editTextStoreAddress.error = "Address must be given"
            binding.editTextStoreAddress.requestFocus()
            return

        }

        val storeTypeId = binding.spinnerStoreType.selectedItemId
        if(storeTypeId == Spinner.INVALID_ROW_ID){
            binding.textViewStore.error = getString(R.string.Type_error)
            binding.spinnerStoreType.requestFocus()
            return

        }


        val savedGame =
            if(store == null){
                insertStore(StoreName,StoreAddress,storeTypeId)

            }else{
                editStore(StoreName,StoreAddress,storeTypeId)
            }


        if(savedGame){

            Toast.makeText(requireContext(), getString(R.string.save_store_success), Toast.LENGTH_LONG).show()
            backtoStoreList()

        }else{
            Toast.makeText(requireContext(), R.string.General_error, Toast.LENGTH_LONG).show()

        }
    }

    private fun editStore(StoreName:String,StoreAddress:String,storeTypeId:Long): Boolean {
        val storeType = Uri.withAppendedPath(ContentProviderGameStore.STORETYPES_ADDRESS, storeTypeId.toString())

        val SelectedStoreType = requireActivity().contentResolver.query(storeType,TDBStoreTypes.ALL_COLUMNS,"${TDBStoreTypes.C_ID} = ?",arrayOf(storeTypeId.toString()),null)

        if((SelectedStoreType == null)) return false
        assert(SelectedStoreType.moveToNext())

        val store = Store(StoreName,StoreAddress,StoreType.fromCursor(SelectedStoreType))
        val storeAddress = Uri.withAppendedPath(ContentProviderGameStore.STORES_ADDRESS,"${this.store!!.id}")

        val UpdatedEntries = requireActivity().contentResolver.update(storeAddress, store.toContentValues(),null,null)

        return UpdatedEntries == 1

    }

    private fun insertStore(
        StoreName:String,
        StoreAddress:String,
        storeTypeId:Long
    ):Boolean {

        val storeType = Uri.withAppendedPath(ContentProviderGameStore.STORETYPES_ADDRESS, storeTypeId.toString())

        val SelectedStoreType = requireActivity().contentResolver.query(storeType,TDBStoreTypes.ALL_COLUMNS,"${TDBStoreTypes.C_ID} = ?",arrayOf(storeTypeId.toString()),null)

        if((SelectedStoreType == null)) return false
        assert(SelectedStoreType.moveToNext())

        val store = Store(StoreName,StoreAddress,StoreType.fromCursor(SelectedStoreType))
        val insertedStoreAddress = requireActivity().contentResolver.insert(ContentProviderGameStore.STORES_ADDRESS, store.toContentValues()) ?: return false

        store.id = ContentUris.parseId(insertedStoreAddress)

        return true

    }

    private fun backtoStoreList() {
        (requireActivity() as MainActivity).updateTitle(getString(R.string.fragment_store_list))
        findNavController().navigate(R.id.action_EditStoreFragment_to_navStore)
    }
}