package com.example.projprogavanc

import android.content.ContentUris
import android.database.Cursor
import android.net.Uri
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.MenuItem
import android.view.View
import android.view.ViewGroup
import android.widget.SimpleCursorAdapter
import android.widget.Spinner
import android.widget.Toast
import androidx.loader.app.LoaderManager
import androidx.loader.content.CursorLoader
import androidx.loader.content.Loader
import androidx.navigation.fragment.findNavController
import com.example.projprogavanc.databinding.FragmentEditGameBinding


class EditGameFragment : Fragment(), LoaderManager.LoaderCallbacks<Cursor>{
    private var _binding: FragmentEditGameBinding? = null

    private val binding get() = _binding!!

    private var game :Game? =null

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment

        _binding = FragmentEditGameBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val activity = activity as MainActivity
        activity.fragment = this
        activity.currMenuId = R.menu.edit_menu

        if(arguments != null){
            game = EditGameFragmentArgs.fromBundle(arguments!!).game

            if(game != null){
                binding.editTextGameName.setText(game!!.name)

            }

        }

        LoaderManager.getInstance(this).initLoader(EditGameFragment.ID_LOADER_GAMETYPE, null, this)

    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    companion object {
        const val ID_LOADER_GAMETYPE = 0
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param id The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    override fun onCreateLoader(id: Int, args: Bundle?): Loader<Cursor> =
        CursorLoader(
            requireContext(),
            ContentProviderGameStore.GAMETYPES_ADDRESS,
            TDBGameTypes.ALL_COLUMNS,
            null,
            null,
            TDBGameTypes.C_TYPE
        )



    /**
     * Called when a previously created loader has finished its load.  Note
     * that normally an application is *not* allowed to commit fragment
     * transactions while in this call, since it can happen after an
     * activity's state is saved.  See [ FragmentManager.openTransaction()][androidx.fragment.app.FragmentManager.beginTransaction] for further discussion on this.
     *
     *
     * This function is guaranteed to be called prior to the release of
     * the last data that was supplied for this Loader.  At this point
     * you should remove all use of the old data (since it will be released
     * soon), but should not do your own release of the data since its Loader
     * owns it and will take care of that.  The Loader will take care of
     * management of its data so you don't have to.  In particular:
     *
     *
     *  *
     *
     *The Loader will monitor for changes to the data, and report
     * them to you through new calls here.  You should not monitor the
     * data yourself.  For example, if the data is a [android.database.Cursor]
     * and you place it in a [android.widget.CursorAdapter], use
     * the [android.widget.CursorAdapter.CursorAdapter] constructor *without* passing
     * in either [android.widget.CursorAdapter.FLAG_AUTO_REQUERY]
     * or [android.widget.CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER]
     * (that is, use 0 for the flags argument).  This prevents the CursorAdapter
     * from doing its own observing of the Cursor, which is not needed since
     * when a change happens you will get a new Cursor throw another call
     * here.
     *  *  The Loader will release the data once it knows the application
     * is no longer using it.  For example, if the data is
     * a [android.database.Cursor] from a [android.content.CursorLoader],
     * you should not call close() on it yourself.  If the Cursor is being placed in a
     * [android.widget.CursorAdapter], you should use the
     * [android.widget.CursorAdapter.swapCursor]
     * method so that the old Cursor is not closed.
     *
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that has finished.
     * @param data The data generated by the Loader.
     */
    override fun onLoadFinished(loader: Loader<Cursor>, data: Cursor?) {
        val adapterGameType = SimpleCursorAdapter(
            requireContext(),
            android.R.layout.simple_list_item_1,
            data,
            arrayOf(TDBGameTypes.C_TYPE),
            intArrayOf(android.R.id.text1),
            0
        )

        binding.spinnerGameType.adapter = adapterGameType

        updateSelectedGameType()
    }

    private fun updateSelectedGameType() {
        if(game == null) return

        val gameTypeId = game!!.type.id

        val lastGameType = binding.spinnerGameType.count - 1

        for (i in 0..lastGameType){
            if(binding.spinnerGameType.getItemIdAtPosition(i) == gameTypeId) {
                binding.spinnerGameType.setSelection(i)
                return
            }
        }
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that is being reset.
     */
    override fun onLoaderReset(loader: Loader<Cursor>) {
        if(_binding == null) return
        binding.spinnerGameType.adapter = null
    }

    fun processOptionMenu(item: MenuItem): Boolean =
        when(item.itemId){
            R.id.action_save ->{
                save()
                true
            }
            R.id.action_cancel ->{
                backtoGameList()
                true
            }
            else -> false
        }

    private fun save() {

        val gameName = binding.editTextGameName.text.toString()
        if(gameName.isBlank()){
            binding.editTextGameName.error = getString(R.string.name_error)
            binding.editTextGameName.requestFocus()
            return

        }

        val gameTypeId = binding.spinnerGameType.selectedItemId
        if(gameTypeId == Spinner.INVALID_ROW_ID){
            binding.textViewGame.error = getString(R.string.Type_error)
            binding.spinnerGameType.requestFocus()
            return

        }


        val savedGame =
            if(game == null){
                insertGameStore(gameName,gameTypeId)

            }else{
                editGameStore(gameName,gameTypeId)
            }


        if(savedGame){

            Toast.makeText(requireContext(), "Game Saved Successfully", Toast.LENGTH_LONG).show()
            backtoGameList()

        }else{
            Toast.makeText(requireContext(), R.string.General_error, Toast.LENGTH_LONG).show()

        }
    }

    private fun editGameStore(gameName: String,gameTypeId: Long): Boolean {
        val gameType = Uri.withAppendedPath(ContentProviderGameStore.GAMETYPES_ADDRESS, gameTypeId.toString())

        val SelectedGameType = requireActivity().contentResolver.query(gameType,TDBGameTypes.ALL_COLUMNS,"${TDBGameTypes.C_ID} = ?",arrayOf(gameTypeId.toString()),null)

        if((SelectedGameType == null)) return false
        assert(SelectedGameType.moveToNext())

        val game = Game(gameName,GameType.fromCursor(SelectedGameType))
        val gameAddress = Uri.withAppendedPath(ContentProviderGameStore.GAMES_ADDRESS,"${this.game!!.id}")

        val UpdatedEntries = requireActivity().contentResolver.update(gameAddress, game.toContentValues(),null,null)

        return UpdatedEntries == 1

    }

    private fun insertGameStore(
        gameName: String,
        gameTypeId: Long
    ):Boolean {

        val gameType = Uri.withAppendedPath(ContentProviderGameStore.GAMETYPES_ADDRESS, gameTypeId.toString())

        val SelectedGameType = requireActivity().contentResolver.query(gameType,TDBGameTypes.ALL_COLUMNS,"${TDBGameTypes.C_ID} = ?",arrayOf(gameTypeId.toString()),null)

        if((SelectedGameType == null)) return false
        assert(SelectedGameType.moveToNext())

        //TODO("Verify if a Game Store with same data already exists in the table if so return false")

        val game = Game(gameName,GameType.fromCursor(SelectedGameType))
        val insertedGameAddress = requireActivity().contentResolver.insert(ContentProviderGameStore.GAMES_ADDRESS, game.toContentValues()) ?: return false

        game.id = ContentUris.parseId(insertedGameAddress)

        return true

    }

    private fun backtoGameList() {
        (requireActivity() as MainActivity).updateTitle(getString(R.string.fragment_game_list))
        findNavController().navigate(R.id.action_EditGameFragment_to_GameList)
    }

}